config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :users
  get '/profile', to: 'users#show'

  get '/events/invited', to: 'events#invited'
  resources :events

  resources :comments

  put '/attendees/:id', to: 'attendees#update', as: :status_attendee

  #resources :attendees #, only: [:show, :update]

  resources :sessions, only: [:new, :create, :destroy]

  get '/login', to: 'sessions#new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendee.rb
class Attendee < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
    validates :title, presence: true
    validates :start_date, presence: true

    belongs_to :user
    has_many :attendees, dependent: :destroy
    has_many :attending_users, through: :attendees, source: :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :email, presence: true, uniqueness: true
    validates :name, presence: true

    has_many :attendees, dependent: :destroy
    has_many :attending_events, through: :attendees, source: :event
    has_many :comments, dependent: :destroy
    has_many :events, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
    
    def update

        attendee_id = params[:id]
        going = params[:going]

        @attendee = Attendee.find(attendee_id)
        
        if going == "true"
            @attendee.status = "true"
        else
            @attendee.status = "false"
        end

        @attendee.save
        
        redirect_to event_path(@attendee.event)
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    def create
        @comment = Comment.new(params.require(:comment).permit(:content, :event_id))
        @comment.user = current_user

        if @comment.content && @comment.content != ''
            @comment.save
        else
            flash[:alert] = "You must write something to post a comment"
        end

        redirect_back(fallback_location: root_path)
    end

    def edit
        @comment = Comment.find(params[:id])
    end

    def update
    end

    def destroy
        @comment = Comment.find(params[:id])
        event = @comment.event_id
        @comment.destroy
        redirect_to event_path(event)
    end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

    def index
        @users_events = current_user.events.order('events.start_date ASC')
    end

    def show
        @event = Event.find(params[:id])
        @users = User.all
        @comments = @event.comments.order('comments.created_at DESC')
        @comment = Comment.new(event_id: @event.id)
    end

    def new
        @event = Event.new
        @users = User.where.not(id: current_user.id)
    end

    def create
        @event = Event.new(event_params)
        @event.user = current_user
        @event.start_date = fix_date(:start_date)

        @guest_index = []
        params.each do |key, val|
            if val == "true"
                @guest_index << key.to_i
            end
        end
    
        @guest_index.each do |ind|
            @event.attending_users << User.find(ind)
        end

        if params[:event][:end_date] && params[:event][:end_date] != ''
            @event.end_date = fix_date(:end_date)
            unless @event.end_date < @event.start_date
                if @event.save
                    redirect_to event_path(@event)
                else
                    flash[:alert] = "Event could not be created, check that event title and start date has been filled"
                    redirect_to new_event_path
                end
            else
                flash[:alert] = "End date/time must be after start date/time"
                redirect_to new_event_path
            end
        else
            if @event.save
                redirect_to event_path(@event)
            else
                flash[:alert] = "Event could not be created, check that event title and start date has been filled"
                redirect_to new_event_path
            end
        end

    end

    def edit
        @event = Event.find(params[:id])
        @users = User.where.not(id: current_user.id)
    end

    def update
        @event = Event.find(params[:id])

        @event.update_attributes(event_params)
        @event.start_date = fix_date(:start_date)

        if params[:event][:end_date]
            @event.end_date = fix_date(:end_date)
        end

        @guest_index = []
        params.each do |key, val|
            if val == "true"
                @guest_index << key.to_i
            end
        end

        @event.attendees.destroy_all

        @guest_index.each do |ind|
            @event.attending_users << User.find(ind)
        end

        if @event.save
            redirect_to event_path(@event)
        else
            redirect_to edit_event_path
        end
    end

    def destroy
        @event = Event.find(params[:id])
        @event.destroy
        redirect_to events_path
    end

    def invited
        @events_inv = current_user.attending_events.order('events.start_date ASC')
    end

private

    def event_params
        params.require(:event).permit(:title, :description, :start_date, :end_date)
    end

    def fix_date(date)
        datestring = params[:event][date]
        unless datestring == ""
            month = datestring[0..1].to_i
            day = datestring[3..4].to_i
            year = datestring[6..9].to_i

            unless datestring.length < 19
                hour = datestring[11..12].to_i
                minute = datestring[14..15].to_i
                ampm = datestring[17..18]
            else
                hour = datestring[11].to_i
                minute = datestring[13..14].to_i
                ampm = datestring[16..17]
            end
            if hour == 12 && ampm.downcase == "pm"
            
            elsif ampm.downcase == "pm"
                hour += 12;
            elsif ampm.downcase == "am" && hour == 12
                hour -= 12
            end
        
            DateTime.new(year,month,day,hour,minute)
        end

    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
    
    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: 'Logged in!'
        else
            flash.now.alert = 'Invalid login credentials - try again!'
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out!"
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user

    if @user.update_attributes(params.require(:user).permit(:name, :email, :interests))
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.interests == nil
      @user.interests = "Nothing, I'm boring.."
    end
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "You have susccessfully signed up!"
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<div class="col-md-offset-3">
    <h1>Edit Event</h1>

    <div>
        <%= form_for @event do |f| %>
            <% if @event.errors.any? %>
            <div class="error_messages">
                <h4 style="color:red">Incomplete information provided</h4>
                <ul>
                <% for message in @event.errors.full_messages %>
                    <li><%= message %></li>
                <% end %>
                </ul>
            </div>
            <% end %>

            <div class="field col-xs-4">
                <%= f.text_field :title, class:"form-control", placeholder:"Event Name" %>
            </div>
            <br></br>
            <div class="container">
                <div class="row">
                    <div class='col-sm-6'>
                        <div class="form-group">
                            <div class='input-group date' id='datetimepicker1'>
                                <%= f.text_field :start_date, class: "form-control", placeholder: @event.start_date %>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">
                        $(function () {
                            $('#datetimepicker1').datetimepicker();
                        });
                    </script>
                </div>
            </div>

            <div class="container">
                <div class="row">
                    <div class='col-sm-6'>
                        <div class="form-group">
                            <div class='input-group date' id='datetimepicker2'>
                                <%= f.text_field :end_date, class:"form-control", placeholder: @event.end_date %>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">
                        $(function () {
                            $('#datetimepicker2').datetimepicker();
                        });
                    </script>
                </div>
            </div>

            <div class ="field col-md-8">
                <%= f.text_area :description,class:"form-control",placeholder:"Description of your event"%>
            </div>
            <div class="guest-list">
                <h3>Invite friends</h3>
                <% @users.each do |user| %>
                    <div class="guest">
                        <% if @event.attending_users.find_by(id: user.id) %>
                            <%= check_box_tag(user.id, true, true, class: "checkbox") %>
                        <% else %>
                            <%= check_box_tag(user.id, true, false, class: "checkbox") %>
                        <% end %>
                        <%= label_tag :checkbox, user.name %>
                    </div>
                <% end %>
            </div>
            <br></br>
            <div class="actions submit-button"><%= f.submit "Edit", class:"btn btn-primary" %></div>
            
        <% end %>
    </div>
</div>

app/views/events/index.html.erb
<div class="event-list">
    <h1>Hosting Events</h1>

    <% @users_events.each do |e| %>
        <div class="event-bubble">
            <% if e.title.length > 24 %>
                <% part_title = e.title[0..24] + "..." %>
            <% end %>
            <% if part_title %>
                <h2 class><%= link_to part_title, event_path(e) %></h2>
            <% else %>
                <h2 class><%= link_to e.title, event_path(e) %></h2>
            <% end %>
            <p>Start: <%= e.start_date.strftime("%a, %b %d, %Y %I:%M%p") %></p>
            <% unless e.end_date == nil %>
                <p>End: <%= e.end_date.strftime("%a, %b %d, %Y %I:%M%p") %></p>
            <% end %>
        </div>
    <% end %>
</div>

app/views/events/invited.html.erb
<div class="event-list">

    <h1>Invited to:</h1>

    <% @events_inv.each do |e| %>
        <div class="event-bubble">
            <% if e.title.length > 24 %>
                <% part_title = e.title[0..24] + "..." %>
            <% end %>
            <% if part_title %>
                <h2 class><%= link_to part_title, event_path(e) %></h2>
            <% else %>
                <h2 class><%= link_to e.title, event_path(e) %></h2>
            <% end %>
            <p>Start: <%= e.start_date.strftime("%a, %b %d, %Y %I:%M%p") %></p>
            <% unless e.end_date == nil %>
                <p>End: <%= e.end_date.strftime("%a, %b %d, %Y %I:%M%p") %></p>
            <% end %>
        </div>
    <% end %>

</div>

app/views/events/new.html.erb
<div class="col-md-offset-3">

    <h1>Create Event</h1>

    <div>
        <% if flash[:alert] %>
            <div class="alert"><%= flash[:alert] %></div>
        <% end %>
        <%= form_for @event do |f| %>
            <% if @event.errors.any? %>
            <div class="error_messages">
                <h4 style="color:red">Incomplete information provided</h4>
                <ul>
                <% for message in @event.errors.full_messages %>
                    <li><%= message %></li>
                <% end %>
                </ul>
            </div>
            <% end %>

            <div class="field col-xs-4">
                <%= f.text_field :title, class:"form-control", placeholder:"Event Name" %>
            </div>
            <br></br>
            <div class="container">
                <div class="row">
                    <div class='col-sm-6'>
                        <div class="form-group">
                            <div class='input-group date' id='datetimepicker1'>
                                <%= f.text_field :start_date, class:"form-control", placeholder:"Start date/time" %>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">
                        $(function () {
                            $('#datetimepicker1').datetimepicker();
                        });
                    </script>
                </div>
            </div>

            <div class="container">
                <div class="row">
                    <div class='col-sm-6'>
                        <div class="form-group">
                            <div class='input-group date' id='datetimepicker2'>
                                <%= f.text_field :end_date, class:"form-control", placeholder:"End date/time" %>
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-calendar"></span>
                                </span>
                            </div>
                        </div>
                    </div>
                    <script type="text/javascript">
                        $(function () {
                            $('#datetimepicker2').datetimepicker();
                        });
                    </script>
                </div>
            </div>

            <div class ="field col-md-8">
                <%= f.text_area :description,class:"form-control",placeholder:"Description of your event"%>
            </div>
            <div class="guest-list">
                <h3>Invite friends</h3>
                <% @users.each do |user| %>
                    <div class="guest">
                        <%= check_box_tag(user.id, true, false, class: "checkbox") %>
                        <%= label_tag :checkbox, user.name %>
                    </div>
                <% end %>
            </div>
            <br></br>
            <div class="actions submit-button"><%= f.submit "Create", class:"btn btn-primary"%></div>
            
        <% end %>
    </div>
</div>

app/views/events/show.html.erb
<div class="wrapper">
    <h1><%= @event.title %></h1>
    <h5>Host: <%= @event.user.name %></h5>
    <h4>Start: <%= @event.start_date.strftime("%a, %b %d, %Y %I:%M%p") %></h4>
    <% unless @event.end_date == nil %>
        <h4>End: <%= @event.end_date.strftime("%a, %b %d, %Y %I:%M%p") %></h4>
    <% end %>
    <br></br>
    <p>Description: <%= @event.description %></p>
    <h4>Invited</h4>
    <% @event.attendees.each do |guest| %>
        <div>
        <% if guest.status == "true" %>
                <i class="fa fa-check-square-o" aria-hidden="true"></i>
            <% elsif guest.status == "false" %>
                <i class="fa fa-frown-o" aria-hidden="true"></i>
            <% else %>
                <i class="fa fa-square-o" aria-hidden="true"></i>
            <% end %>
            <p class="listed-guests"><%= @users.find(guest.user_id).name %></p>
        </div>
    <% end %>
    <% if current_user == @event.user %>
        <%= link_to "Edit", edit_event_path %>
        <%= link_to "Delete", event_path(@event), method: :delete, data: { confirm: "Are you sure you want to delete this event?"} %>
    <% else %>

        <div>
            <%= link_to "Going!", status_attendee_path(@event.attendees.find_by(user_id: current_user.id), :going => true), method: :put, class:"btn btn-success" %>

            <%= link_to "Not Going", status_attendee_path(@event.attendees.find_by(user_id: current_user.id), :going => false), method: :put, class:"btn btn-danger" %>
            
        </div>

    <% end %>
</div>

<div class="wrapper">
    <% if flash[:alert] %>
        <div><%= flash[:alert] %></div>
    <% end %>
    <%= form_for @comment do |f| %>
        <%= f.text_field :content, class: "form-control", placeholder: "Write your comment here.." %>
        <%= f.hidden_field :event_id %> 
        <div class="actions comment-btn"><%= f.submit "Comment", class:"btn-sm btn-primary" %></div>
    <% end %>
</div>


<% @comments.each do |comment| %>
    <div class="wrapper">
        <div class="comment-title">
            <h4 class="comment-name"><%= comment.user.name %></h4>
            <p class="comment-time">
                <%= comment.created_at.in_time_zone("America/Los_Angeles").strftime('%a, %d %b %Y %H:%M %p') %> 
                <% if current_user == comment.user %>
                <%= link_to "Delete", comment_path(comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?"} %>
                <% end %>
            </p>
        </div>
        <p><%= comment.content %></p>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduAll</title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'scheduall_logo.png' %>

    <link href="https://fonts.googleapis.com/css?family=Cookie|Damion|Roboto" rel="stylesheet">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <script src="https://use.fontawesome.com/7a20da659b.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="/">
            <%= image_tag "scheduall_logo.png", :class => "logo-nav" %>
          </a>
        </div>
        <div class="nav-links">
          <% if current_user %>
            <%= link_to "Create Event", new_event_path %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to "Hosting Events", events_path %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to "Invitations", events_invited_path %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to current_user.name, profile_path %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to 'Log Out', session_path('dummy'), method: :delete, class: "header_link"%>
          <% else %>
            <%= link_to 'Log In', login_path, class: "header_link" %>
            &nbsp;&nbsp;|&nbsp;&nbsp;
            <%= link_to 'Sign Up', new_user_path, class: "header_link" %>
          <% end %>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="col-md-12">
    <h1 class="profile-title col-md-offset-4">Edit Profile</h1>

    <div class="profile-info col-md-offset-4">
        <%= form_for @user do |user| %>
            <% if @user.errors.any? %>
                <div class="error_messages">
                <h2>Invalid information</h2>
                <ul>
                    <% for message in @user.errors.full_messages %>
                    <li><%= message %></li>
                    <% end %>
                </ul>
                </div>
            <% end %>
            <div>
                <%= user.label :name %> <%= user.text_field :name %>
            </div>
            <div>
                <%= user.label :email %>
                <%= user.text_field :email %>
            <div>
                <%= user.label :interests %>
                <%= user.text_field :interests %>
            </div>
            <%= user.submit "Save" %>

            <!--<%= button_to "Save", user_path(@user.id), :method => "put" %> -->
        <% end %>
    </div>

</div>

app/views/users/new.html.erb
<div class="col-md-offset-4">
  <h1>Sign Up</h1>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>Form is invalid</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field input-group sign-in col-xs-4">
      <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
      <%= f.text_field :name,class:"form-control", placeholder:"Your Name" %>
    </div>
    <div class="field input-group sign-in col-xs-4">
      <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
      <%= f.text_field :email, class:"form-control", placeholder:"Email" %>
    </div>
    <div class="field input-group sign-in col-xs-4">
      <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
      <%= f.password_field :password,class:"form-control", placeholder:"Password" %>
    </div>
    <div class="field input-group sign-in col-xs-4">
      <span class="input-group-addon"><i class="glyphicon glyphicon-lock"></i></span>
      <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirm Password" %>
    </div>
    <div class="actions"><%= f.submit "Sign up", class:"btn btn-primary"%></div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="col-md-12">
    
    
    <div class="profile col-md-offset-3">
        <%= image_tag "pug_profile.png", class:"profile-pic" %>
        <div class="profile-info">
            <h1 class="profile-title"><%= @user.name %></h1>
            <p>E-mail: <%= @user.email %></p>
            <p>Interests: <%= @user.interests %></p>
            <%= button_to "Edit", edit_user_path(@user.id), :method => "get", class:"btn btn-primary" %>
        </div>
    </div>

</div>

app/views/welcome/index.html.erb
<h1 class="main-title">ScheduAll <%= image_tag "scheduall_logo.png", :class => "logo" %></h1>

<div class="headings">
    <h2 class="sub-head">Host</h2>

    <h2 class="sub-head">Attend</h2>

    <h2 class="sub-head">Party</h2>
    
    <div>
        <i class="icons fa fa-envelope fa-5x" aria-hidden="true"></i>

        <i class="icons fa fa-check-square fa-5x" aria-hidden="true"></i>

        <i class="icons fa fa-users fa-5x" aria-hidden="true"></i>
    </div>
</div>